FROM rocker/r-ver:4.3.3

RUN apt-get update -y && apt-get install -y \
    libssl-dev \
    libsasl2-dev \
    libcurl4-openssl-dev \
    libcurl4 \
    libsodium-dev \
    libxml2-dev \
    libfontconfig1-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libuv1-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN install2.r --error \
    plumber \
    here \
    cli \
    glue \
    purrr \
    mongolite \
    httr2 \
    jsonlite \
    promises \
    future

WORKDIR /app

COPY mcp_server /app/mcp_server


EXPOSE 8000

CMD ["Rscript", "mcp_server/run_server.r"]
