FROM rocker/r-ver:4.3.3

RUN apt-get update -y && apt-get install -y \
    libssl-dev \
    libsasl2-dev \
    libcurl4-openssl-dev \
    libcurl4 \
    && rm -rf /var/lib/apt/lists/*

RUN Rscript -e "install.packages(c('plumber', 'here', 'cli', 'glue', 'purrr', 'mongolite', 'httr2', 'jsonlite', 'promises', 'future'), repos = 'https://cloud.r-project.org')"

WORKDIR /app

COPY mcp_server /app/mcp_server


EXPOSE 8000

CMD ["Rscript", "mcp_server/run_server.r"]
